# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiAdminPage.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 565)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"    background-image: url(:/bgi/images/greyMetal.jpg);\n"
"\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(140, 10, 281, 71))
        self.label_logo.setStyleSheet("background-image: url(:/logo/images/hawkeye_logo.png);\n"
"background-color: rgb(202, 202, 202);")
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.label_propic_img = QtWidgets.QLabel(self.centralwidget)
        self.label_propic_img.setGeometry(QtCore.QRect(390, 160, 120, 140))
        self.label_propic_img.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.label_propic_img.setText("")
        self.label_propic_img.setObjectName("label_propic_img")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(41, 150, 301, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_userid = QtWidgets.QLabel(self.layoutWidget)
        self.label_userid.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_userid.setObjectName("label_userid")
        self.gridLayout.addWidget(self.label_userid, 0, 0, 1, 1)
        self.lineEdit_userid = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_userid.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_userid.setObjectName("lineEdit_userid")
        self.gridLayout.addWidget(self.lineEdit_userid, 0, 1, 1, 1)
        self.label_firstname = QtWidgets.QLabel(self.layoutWidget)
        self.label_firstname.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_firstname.setObjectName("label_firstname")
        self.gridLayout.addWidget(self.label_firstname, 1, 0, 1, 1)
        self.lineEdit_firstname = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_firstname.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_firstname.setObjectName("lineEdit_firstname")
        self.gridLayout.addWidget(self.lineEdit_firstname, 1, 1, 1, 1)
        self.label_lastname = QtWidgets.QLabel(self.layoutWidget)
        self.label_lastname.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_lastname.setObjectName("label_lastname")
        self.gridLayout.addWidget(self.label_lastname, 2, 0, 1, 1)
        self.lineEdit_lastname = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_lastname.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_lastname.setObjectName("lineEdit_lastname")
        self.gridLayout.addWidget(self.lineEdit_lastname, 2, 1, 1, 1)
        self.label_username = QtWidgets.QLabel(self.layoutWidget)
        self.label_username.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_username.setObjectName("label_username")
        self.gridLayout.addWidget(self.label_username, 3, 0, 1, 1)
        self.lineEdit_username = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_username.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.gridLayout.addWidget(self.lineEdit_username, 3, 1, 1, 1)
        self.label_emailid = QtWidgets.QLabel(self.layoutWidget)
        self.label_emailid.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_emailid.setObjectName("label_emailid")
        self.gridLayout.addWidget(self.label_emailid, 4, 0, 1, 1)
        self.lineEdit_emailid = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_emailid.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_emailid.setObjectName("lineEdit_emailid")
        self.gridLayout.addWidget(self.lineEdit_emailid, 4, 1, 1, 1)
        self.label_mobno = QtWidgets.QLabel(self.layoutWidget)
        self.label_mobno.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_mobno.setObjectName("label_mobno")
        self.gridLayout.addWidget(self.label_mobno, 5, 0, 1, 1)
        self.lineEdit_mobileno = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_mobileno.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.lineEdit_mobileno.setObjectName("lineEdit_mobileno")
        self.gridLayout.addWidget(self.lineEdit_mobileno, 5, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 400, 401, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_updateuser = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_updateuser.setObjectName("pushButton_updateuser")
        self.horizontalLayout.addWidget(self.pushButton_updateuser)
        self.pushButton_adduser = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_adduser.setObjectName("pushButton_adduser")
        self.horizontalLayout.addWidget(self.pushButton_adduser)
        self.pushButton_deleteuser = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_deleteuser.setObjectName("pushButton_deleteuser")
        self.horizontalLayout.addWidget(self.pushButton_deleteuser)
        self.pushButton_searchuser = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_searchuser.setObjectName("pushButton_searchuser")
        self.horizontalLayout.addWidget(self.pushButton_searchuser)
        self.pushButton_clear = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout.addWidget(self.pushButton_clear)
        self.pushButton_clear.raise_()
        self.pushButton_searchuser.raise_()
        self.pushButton_deleteuser.raise_()
        self.pushButton_adduser.raise_()
        self.pushButton_updateuser.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 593, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_userid.setText(_translate("MainWindow", "Use Id:"))
        self.label_firstname.setText(_translate("MainWindow", "First Name:"))
        self.label_lastname.setText(_translate("MainWindow", "Last Name:"))
        self.label_username.setText(_translate("MainWindow", "User Name:"))
        self.label_emailid.setText(_translate("MainWindow", "Email Id:"))
        self.label_mobno.setText(_translate("MainWindow", "Mobile No:"))
        self.pushButton_updateuser.setText(_translate("MainWindow", "Update User"))
        self.pushButton_adduser.setText(_translate("MainWindow", "Add User"))
        self.pushButton_deleteuser.setText(_translate("MainWindow", "Delete User"))
        self.pushButton_searchuser.setText(_translate("MainWindow", "Search User"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))

from resource.qrc import adminpage_rc
