# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiAdminPage.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(633, 683)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"    background-image: url(:/bgi/images/greyMetal.jpg);\n"
"\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(210, 20, 281, 71))
        self.label_logo.setStyleSheet("background-image: url(:/logo/images/hawkeye_logo.png);\n"
"background-color: rgb(202, 202, 202);")
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.label_propic_img = QtWidgets.QLabel(self.centralwidget)
        self.label_propic_img.setGeometry(QtCore.QRect(110, 130, 120, 140))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_propic_img.sizePolicy().hasHeightForWidth())
        self.label_propic_img.setSizePolicy(sizePolicy)
        self.label_propic_img.setStyleSheet("background-image: url(:/icon/images/profilePicture.png);")
        self.label_propic_img.setText("")
        self.label_propic_img.setObjectName("label_propic_img")
        self.groupBox_SearchBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_SearchBox.setGeometry(QtCore.QRect(350, 100, 271, 261))
        self.groupBox_SearchBox.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 255, 255);")
        self.groupBox_SearchBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_SearchBox.setObjectName("groupBox_SearchBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_SearchBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 70, 231, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_SearchText = QtWidgets.QLabel(self.layoutWidget)
        self.label_SearchText.setObjectName("label_SearchText")
        self.gridLayout_3.addWidget(self.label_SearchText, 0, 0, 1, 1)
        self.lineEdit_SearchText = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_SearchText.setObjectName("lineEdit_SearchText")
        self.gridLayout_3.addWidget(self.lineEdit_SearchText, 0, 1, 1, 1)
        self.label_SearchBy = QtWidgets.QLabel(self.layoutWidget)
        self.label_SearchBy.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.label_SearchBy.setObjectName("label_SearchBy")
        self.gridLayout_3.addWidget(self.label_SearchBy, 1, 0, 1, 1)
        self.comboBox_SearchBy = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_SearchBy.setStyleSheet("color: rgb(0, 0, 0);")
        self.comboBox_SearchBy.setObjectName("comboBox_SearchBy")
        self.gridLayout_3.addWidget(self.comboBox_SearchBy, 1, 1, 1, 1)
        self.pushButton_searchuser = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_searchuser.setGeometry(QtCore.QRect(440, 280, 91, 21))
        self.pushButton_searchuser.setObjectName("pushButton_searchuser")
        self.pushButton_Edit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Edit.setGeometry(QtCore.QRect(250, 260, 75, 23))
        self.pushButton_Edit.setObjectName("pushButton_Edit")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 100, 331, 471))
        self.groupBox.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 255, 255);")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(11, 430, 71, 21))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(100, 430, 211, 25))
        self.comboBox.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(21, 570, 311, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_adduser = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_adduser.setObjectName("pushButton_adduser")
        self.gridLayout_2.addWidget(self.pushButton_adduser, 0, 0, 1, 1)
        self.pushButton_updateuser = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_updateuser.setObjectName("pushButton_updateuser")
        self.gridLayout_2.addWidget(self.pushButton_updateuser, 0, 1, 1, 1)
        self.pushButton_deleteuser = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_deleteuser.setObjectName("pushButton_deleteuser")
        self.gridLayout_2.addWidget(self.pushButton_deleteuser, 0, 2, 1, 1)
        self.pushButton_ResetPassword = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_ResetPassword.setObjectName("pushButton_ResetPassword")
        self.gridLayout_2.addWidget(self.pushButton_ResetPassword, 1, 0, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout_2.addWidget(self.pushButton_clear, 1, 1, 1, 1)
        self.pushButton_changePic = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_changePic.setObjectName("pushButton_changePic")
        self.gridLayout_2.addWidget(self.pushButton_changePic, 1, 2, 1, 1)
        self.pushButton_Logout = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Logout.setGeometry(QtCore.QRect(520, 42, 81, 31))
        self.pushButton_Logout.setObjectName("pushButton_Logout")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(22, 300, 301, 221))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_userid = QtWidgets.QLabel(self.layoutWidget2)
        self.label_userid.setStyleSheet("")
        self.label_userid.setObjectName("label_userid")
        self.gridLayout_4.addWidget(self.label_userid, 0, 0, 1, 1)
        self.lineEdit_UserIdText = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_UserIdText.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_UserIdText.setReadOnly(True)
        self.lineEdit_UserIdText.setObjectName("lineEdit_UserIdText")
        self.gridLayout_4.addWidget(self.lineEdit_UserIdText, 0, 1, 1, 1)
        self.label_firstname = QtWidgets.QLabel(self.layoutWidget2)
        self.label_firstname.setStyleSheet("")
        self.label_firstname.setObjectName("label_firstname")
        self.gridLayout_4.addWidget(self.label_firstname, 1, 0, 1, 1)
        self.lineEdit_firstname = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_firstname.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_firstname.setObjectName("lineEdit_firstname")
        self.gridLayout_4.addWidget(self.lineEdit_firstname, 1, 1, 1, 1)
        self.label_lastname = QtWidgets.QLabel(self.layoutWidget2)
        self.label_lastname.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_lastname.setObjectName("label_lastname")
        self.gridLayout_4.addWidget(self.label_lastname, 2, 0, 1, 1)
        self.lineEdit_lastname = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_lastname.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_lastname.setObjectName("lineEdit_lastname")
        self.gridLayout_4.addWidget(self.lineEdit_lastname, 2, 1, 1, 1)
        self.label_username = QtWidgets.QLabel(self.layoutWidget2)
        self.label_username.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_username.setObjectName("label_username")
        self.gridLayout_4.addWidget(self.label_username, 3, 0, 1, 1)
        self.lineEdit_username = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_username.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.gridLayout_4.addWidget(self.lineEdit_username, 3, 1, 1, 1)
        self.label_emailid = QtWidgets.QLabel(self.layoutWidget2)
        self.label_emailid.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_emailid.setObjectName("label_emailid")
        self.gridLayout_4.addWidget(self.label_emailid, 4, 0, 1, 1)
        self.lineEdit_emailid = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_emailid.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_emailid.setObjectName("lineEdit_emailid")
        self.gridLayout_4.addWidget(self.lineEdit_emailid, 4, 1, 1, 1)
        self.label_mobno = QtWidgets.QLabel(self.layoutWidget2)
        self.label_mobno.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_mobno.setObjectName("label_mobno")
        self.gridLayout_4.addWidget(self.label_mobno, 5, 0, 1, 1)
        self.lineEdit_mobileno = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_mobileno.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.lineEdit_mobileno.setObjectName("lineEdit_mobileno")
        self.gridLayout_4.addWidget(self.lineEdit_mobileno, 5, 1, 1, 1)
        self.groupBox.raise_()
        self.groupBox_SearchBox.raise_()
        self.pushButton_searchuser.raise_()
        self.label_logo.raise_()
        self.label_propic_img.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.pushButton_Edit.raise_()
        self.pushButton_Logout.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_SearchBox.setTitle(_translate("MainWindow", "Search Box"))
        self.label_SearchText.setText(_translate("MainWindow", "Search Text"))
        self.label_SearchBy.setText(_translate("MainWindow", "Search By"))
        self.pushButton_searchuser.setText(_translate("MainWindow", "Search User"))
        self.pushButton_Edit.setText(_translate("MainWindow", "Edit"))
        self.groupBox.setTitle(_translate("MainWindow", "User Information"))
        self.label.setText(_translate("MainWindow", "User Type:"))
        self.pushButton_adduser.setText(_translate("MainWindow", "Add User"))
        self.pushButton_updateuser.setText(_translate("MainWindow", "Update User"))
        self.pushButton_deleteuser.setText(_translate("MainWindow", "Delete User"))
        self.pushButton_ResetPassword.setText(_translate("MainWindow", "Reset Password"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_changePic.setText(_translate("MainWindow", "Change Profile Picture"))
        self.pushButton_Logout.setText(_translate("MainWindow", "Logout"))
        self.label_userid.setText(_translate("MainWindow", "Use Id:"))
        self.label_firstname.setText(_translate("MainWindow", "First Name:"))
        self.label_lastname.setText(_translate("MainWindow", "Last Name:"))
        self.label_username.setText(_translate("MainWindow", "User Name:"))
        self.label_emailid.setText(_translate("MainWindow", "Email Id:"))
        self.label_mobno.setText(_translate("MainWindow", "Mobile No:"))

from resource.qrc import adminpage_rc
