# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiOfficerPage.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1372, 681)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1191, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_page1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_page1.sizePolicy().hasHeightForWidth())
        self.pushButton_page1.setSizePolicy(sizePolicy)
        self.pushButton_page1.setObjectName("pushButton_page1")
        self.horizontalLayout.addWidget(self.pushButton_page1)
        self.pushButton_page2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_page2.sizePolicy().hasHeightForWidth())
        self.pushButton_page2.setSizePolicy(sizePolicy)
        self.pushButton_page2.setObjectName("pushButton_page2")
        self.horizontalLayout.addWidget(self.pushButton_page2)
        self.pushButton_page3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_page3.sizePolicy().hasHeightForWidth())
        self.pushButton_page3.setSizePolicy(sizePolicy)
        self.pushButton_page3.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton_page3.setObjectName("pushButton_page3")
        self.horizontalLayout.addWidget(self.pushButton_page3)
        self.pushButton_page4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_page4.sizePolicy().hasHeightForWidth())
        self.pushButton_page4.setSizePolicy(sizePolicy)
        self.pushButton_page4.setObjectName("pushButton_page4")
        self.horizontalLayout.addWidget(self.pushButton_page4)
        self.pushButton_page5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_page5.sizePolicy().hasHeightForWidth())
        self.pushButton_page5.setSizePolicy(sizePolicy)
        self.pushButton_page5.setObjectName("pushButton_page5")
        self.horizontalLayout.addWidget(self.pushButton_page5)
        self.pushButton_page6 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_page6.sizePolicy().hasHeightForWidth())
        self.pushButton_page6.setSizePolicy(sizePolicy)
        self.pushButton_page6.setObjectName("pushButton_page6")
        self.horizontalLayout.addWidget(self.pushButton_page6)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 80, 1251, 531))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_video_tab = QtWidgets.QWidget()
        self.page_video_tab.setObjectName("page_video_tab")
        self.tableWidget_Recording = QtWidgets.QTableWidget(self.page_video_tab)
        self.tableWidget_Recording.setGeometry(QtCore.QRect(670, 0, 511, 411))
        self.tableWidget_Recording.setObjectName("tableWidget_Recording")
        self.tableWidget_Recording.setColumnCount(5)
        self.tableWidget_Recording.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Recording.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Recording.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Recording.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Recording.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Recording.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Recording.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Recording.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Recording.setHorizontalHeaderItem(4, item)
        self.label_player = QtWidgets.QLabel(self.page_video_tab)
        self.label_player.setGeometry(QtCore.QRect(10, 0, 640, 480))
        self.label_player.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"RR")
        self.label_player.setText("")
        self.label_player.setObjectName("label_player")
        self.layoutWidget = QtWidgets.QWidget(self.page_video_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 490, 561, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_start = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_2.addWidget(self.pushButton_start)
        self.pushButton_stop = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout_2.addWidget(self.pushButton_stop)
        self.pushButton_startRec = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_startRec.setObjectName("pushButton_startRec")
        self.horizontalLayout_2.addWidget(self.pushButton_startRec)
        self.pushButton_stopRec = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_stopRec.setObjectName("pushButton_stopRec")
        self.horizontalLayout_2.addWidget(self.pushButton_stopRec)
        self.line_2 = QtWidgets.QFrame(self.page_video_tab)
        self.line_2.setGeometry(QtCore.QRect(650, -20, 20, 501))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(self.page_video_tab)
        self.line.setGeometry(QtCore.QRect(1180, 0, 20, 541))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.stackedWidget.addWidget(self.page_video_tab)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayoutWidget.raise_()
        self.stackedWidget.raise_()
        self.pushButton_page6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1372, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HawkEye"))
        self.pushButton_page1.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_page2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_page3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_page4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_page5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_page6.setText(_translate("MainWindow", "PushButton"))
        item = self.tableWidget_Recording.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_Recording.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_Recording.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_Recording.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_Recording.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.tableWidget_Recording.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_Recording.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_Recording.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Duration"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.pushButton_startRec.setText(_translate("MainWindow", "Start Recording"))
        self.pushButton_stopRec.setText(_translate("MainWindow", "Stop Recording"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

