# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiUserPage.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UserWindow(object):
    def setupUi(self, UserWindow):
        UserWindow.setObjectName("UserWindow")
        UserWindow.resize(1372, 730)
        UserWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(UserWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"    background-image: url(:/UserPage/images/greyMetal.jpg);\n"
"    \n"
"\n"
"}\n"
"QTableWidget#tableWidget_Recording{\n"
"    background-color: rgb(170, 170, 255);\n"
"\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 80, 1371, 621))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_video_tab = QtWidgets.QWidget()
        self.page_video_tab.setObjectName("page_video_tab")
        self.label_player = QtWidgets.QLabel(self.page_video_tab)
        self.label_player.setGeometry(QtCore.QRect(10, 10, 640, 480))
        self.label_player.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 0, 0);")
        self.label_player.setText("")
        self.label_player.setObjectName("label_player")
        self.line_2 = QtWidgets.QFrame(self.page_video_tab)
        self.line_2.setGeometry(QtCore.QRect(650, -20, 20, 511))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(self.page_video_tab)
        self.line.setGeometry(QtCore.QRect(1090, 0, 20, 621))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_prediction = QtWidgets.QLabel(self.page_video_tab)
        self.label_prediction.setGeometry(QtCore.QRect(1120, 0, 231, 51))
        self.label_prediction.setStyleSheet("font: 75 24pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(180, 0, 0);\n"
"background-color: rgb(170, 255, 255);")
        self.label_prediction.setAlignment(QtCore.Qt.AlignCenter)
        self.label_prediction.setObjectName("label_prediction")
        self.layoutWidget = QtWidgets.QWidget(self.page_video_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(1120, 60, 231, 21))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_type = QtWidgets.QLabel(self.layoutWidget)
        self.label_type.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_type.setAlignment(QtCore.Qt.AlignCenter)
        self.label_type.setObjectName("label_type")
        self.horizontalLayout_2.addWidget(self.label_type)
        self.label_confidence = QtWidgets.QLabel(self.layoutWidget)
        self.label_confidence.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_confidence.setAlignment(QtCore.Qt.AlignCenter)
        self.label_confidence.setObjectName("label_confidence")
        self.horizontalLayout_2.addWidget(self.label_confidence)
        self.label_msg = QtWidgets.QLabel(self.page_video_tab)
        self.label_msg.setGeometry(QtCore.QRect(10, 505, 141, 21))
        self.label_msg.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.label_msg.setText("")
        self.label_msg.setObjectName("label_msg")
        self.listWidgetResults = QtWidgets.QListWidget(self.page_video_tab)
        self.listWidgetResults.setGeometry(QtCore.QRect(1120, 90, 231, 381))
        self.listWidgetResults.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.listWidgetResults.setObjectName("listWidgetResults")
        self.widget = QtWidgets.QWidget(self.page_video_tab)
        self.widget.setGeometry(QtCore.QRect(160, 501, 320, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_start = QtWidgets.QPushButton(self.widget)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout.addWidget(self.pushButton_start)
        self.pushButton_stop = QtWidgets.QPushButton(self.widget)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout.addWidget(self.pushButton_stop)
        self.pushButton_startRec = QtWidgets.QPushButton(self.widget)
        self.pushButton_startRec.setObjectName("pushButton_startRec")
        self.horizontalLayout.addWidget(self.pushButton_startRec)
        self.pushButton_stopRec = QtWidgets.QPushButton(self.widget)
        self.pushButton_stopRec.setObjectName("pushButton_stopRec")
        self.horizontalLayout.addWidget(self.pushButton_stopRec)
        self.layoutWidget.raise_()
        self.label_player.raise_()
        self.layoutWidget.raise_()
        self.line_2.raise_()
        self.line.raise_()
        self.label_prediction.raise_()
        self.label_msg.raise_()
        self.listWidgetResults.raise_()
        self.stackedWidget.addWidget(self.page_video_tab)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableWidget_Recording = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_Recording.setGeometry(QtCore.QRect(690, 10, 411, 291))
        self.tableWidget_Recording.setStyleSheet("")
        self.tableWidget_Recording.setObjectName("tableWidget_Recording")
        self.tableWidget_Recording.setColumnCount(4)
        self.tableWidget_Recording.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Recording.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Recording.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Recording.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Recording.setHorizontalHeaderItem(3, item)
        self.label_opdirtext = QtWidgets.QLabel(self.page_2)
        self.label_opdirtext.setGeometry(QtCore.QRect(790, 320, 311, 21))
        self.label_opdirtext.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_opdirtext.setText("")
        self.label_opdirtext.setObjectName("label_opdirtext")
        self.pushButton_FileDialog = QtWidgets.QPushButton(self.page_2)
        self.pushButton_FileDialog.setGeometry(QtCore.QRect(690, 320, 91, 23))
        self.pushButton_FileDialog.setObjectName("pushButton_FileDialog")
        self.label_player_2 = QtWidgets.QLabel(self.page_2)
        self.label_player_2.setGeometry(QtCore.QRect(30, 10, 640, 480))
        self.label_player_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 0, 0);")
        self.label_player_2.setText("")
        self.label_player_2.setObjectName("label_player_2")
        self.pushButton_vstop = QtWidgets.QPushButton(self.page_2)
        self.pushButton_vstop.setGeometry(QtCore.QRect(331, 540, 75, 23))
        self.pushButton_vstop.setObjectName("pushButton_vstop")
        self.pushButton_play = QtWidgets.QPushButton(self.page_2)
        self.pushButton_play.setGeometry(QtCore.QRect(250, 540, 75, 23))
        self.pushButton_play.setObjectName("pushButton_play")
        self.comboBox = QtWidgets.QComboBox(self.page_2)
        self.comboBox.setGeometry(QtCore.QRect(790, 370, 131, 21))
        self.comboBox.setObjectName("comboBox")
        self.label_date = QtWidgets.QLabel(self.page_2)
        self.label_date.setGeometry(QtCore.QRect(690, 370, 91, 21))
        self.label_date.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_date.setObjectName("label_date")
        self.pushButton_show = QtWidgets.QPushButton(self.page_2)
        self.pushButton_show.setGeometry(QtCore.QRect(940, 370, 75, 23))
        self.pushButton_show.setObjectName("pushButton_show")
        self.pushButton_today = QtWidgets.QPushButton(self.page_2)
        self.pushButton_today.setGeometry(QtCore.QRect(1030, 370, 75, 23))
        self.pushButton_today.setObjectName("pushButton_today")
        self.horizontalSlider = QtWidgets.QSlider(self.page_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 510, 641, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.stackedWidget.addWidget(self.page_2)
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(500, 9, 280, 61))
        self.label_logo.setStyleSheet("background-color: rgb(208, 208, 208);\n"
"\n"
"background-image: url(:/UserPage/images/hawkeye_logo.png);")
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.pushButton_page1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_page1.setGeometry(QtCore.QRect(11, 11, 81, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_page1.sizePolicy().hasHeightForWidth())
        self.pushButton_page1.setSizePolicy(sizePolicy)
        self.pushButton_page1.setStyleSheet("background-image: url(:/UserPage/images/video-icon.jpg);\n"
"")
        self.pushButton_page1.setText("")
        self.pushButton_page1.setFlat(False)
        self.pushButton_page1.setObjectName("pushButton_page1")
        self.pushButton_page2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_page2.setGeometry(QtCore.QRect(110, 10, 91, 61))
        self.pushButton_page2.setObjectName("pushButton_page2")
        UserWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UserWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1372, 21))
        self.menubar.setObjectName("menubar")
        UserWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UserWindow)
        self.statusbar.setObjectName("statusbar")
        UserWindow.setStatusBar(self.statusbar)

        self.retranslateUi(UserWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UserWindow)

    def retranslateUi(self, UserWindow):
        _translate = QtCore.QCoreApplication.translate
        UserWindow.setWindowTitle(_translate("UserWindow", "HawkEye"))
        self.label_prediction.setText(_translate("UserWindow", "Prediction"))
        self.label_type.setText(_translate("UserWindow", "Type"))
        self.label_confidence.setText(_translate("UserWindow", "Confidence"))
        self.pushButton_start.setText(_translate("UserWindow", "Start"))
        self.pushButton_stop.setText(_translate("UserWindow", "Stop"))
        self.pushButton_startRec.setText(_translate("UserWindow", "Start Rec"))
        self.pushButton_stopRec.setText(_translate("UserWindow", "Stop Rec"))
        item = self.tableWidget_Recording.horizontalHeaderItem(0)
        item.setText(_translate("UserWindow", "File Name"))
        item = self.tableWidget_Recording.horizontalHeaderItem(1)
        item.setText(_translate("UserWindow", "Date/Time"))
        item = self.tableWidget_Recording.horizontalHeaderItem(2)
        item.setText(_translate("UserWindow", "Size"))
        item = self.tableWidget_Recording.horizontalHeaderItem(3)
        item.setText(_translate("UserWindow", "Duration"))
        self.pushButton_FileDialog.setText(_translate("UserWindow", "OutPut Folder"))
        self.pushButton_vstop.setText(_translate("UserWindow", "Stop"))
        self.pushButton_play.setText(_translate("UserWindow", "Play"))
        self.label_date.setText(_translate("UserWindow", "Date Select"))
        self.pushButton_show.setText(_translate("UserWindow", "Show"))
        self.pushButton_today.setText(_translate("UserWindow", "Today"))
        self.pushButton_page2.setText(_translate("UserWindow", "Player"))

from resource.qrc import UserPage_rc
