# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiUserPage.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UserWindow(object):
    def setupUi(self, UserWindow):
        UserWindow.setObjectName("UserWindow")
        UserWindow.resize(1377, 730)
        UserWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(UserWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"    background-image: url(:/LoginPage/images/bg2.jpg);\n"
"}\n"
"QTableWidget#tableWidget_Recording{\n"
"    background-color: rgb(170, 170, 255);\n"
"\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 80, 1371, 621))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_video_tab = QtWidgets.QWidget()
        self.page_video_tab.setObjectName("page_video_tab")
        self.tableWidget_Recording = QtWidgets.QTableWidget(self.page_video_tab)
        self.tableWidget_Recording.setGeometry(QtCore.QRect(670, 0, 411, 411))
        self.tableWidget_Recording.setStyleSheet("")
        self.tableWidget_Recording.setObjectName("tableWidget_Recording")
        self.tableWidget_Recording.setColumnCount(4)
        self.tableWidget_Recording.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Recording.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Recording.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Recording.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Recording.setHorizontalHeaderItem(3, item)
        self.label_player = QtWidgets.QLabel(self.page_video_tab)
        self.label_player.setGeometry(QtCore.QRect(10, 0, 640, 480))
        self.label_player.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 0, 0);")
        self.label_player.setText("")
        self.label_player.setObjectName("label_player")
        self.line_2 = QtWidgets.QFrame(self.page_video_tab)
        self.line_2.setGeometry(QtCore.QRect(650, -20, 20, 501))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(self.page_video_tab)
        self.line.setGeometry(QtCore.QRect(1180, 0, 20, 541))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_FileDialog = QtWidgets.QPushButton(self.page_video_tab)
        self.pushButton_FileDialog.setGeometry(QtCore.QRect(670, 420, 91, 23))
        self.pushButton_FileDialog.setObjectName("pushButton_FileDialog")
        self.label = QtWidgets.QLabel(self.page_video_tab)
        self.label.setGeometry(QtCore.QRect(770, 420, 311, 21))
        self.label.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalSlider_video = QtWidgets.QSlider(self.page_video_tab)
        self.horizontalSlider_video.setGeometry(QtCore.QRect(100, 490, 551, 22))
        self.horizontalSlider_video.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_video.setObjectName("horizontalSlider_video")
        self.label_vtime = QtWidgets.QLabel(self.page_video_tab)
        self.label_vtime.setGeometry(QtCore.QRect(10, 490, 81, 21))
        self.label_vtime.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_vtime.setText("")
        self.label_vtime.setObjectName("label_vtime")
        self.widget = QtWidgets.QWidget(self.page_video_tab)
        self.widget.setGeometry(QtCore.QRect(130, 540, 401, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_prev = QtWidgets.QPushButton(self.widget)
        self.pushButton_prev.setObjectName("pushButton_prev")
        self.horizontalLayout_2.addWidget(self.pushButton_prev)
        self.pushButton_pause = QtWidgets.QPushButton(self.widget)
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.horizontalLayout_2.addWidget(self.pushButton_pause)
        self.pushButton_play = QtWidgets.QPushButton(self.widget)
        self.pushButton_play.setObjectName("pushButton_play")
        self.horizontalLayout_2.addWidget(self.pushButton_play)
        self.pushButton_vstop = QtWidgets.QPushButton(self.widget)
        self.pushButton_vstop.setObjectName("pushButton_vstop")
        self.horizontalLayout_2.addWidget(self.pushButton_vstop)
        self.pushButton_next = QtWidgets.QPushButton(self.widget)
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout_2.addWidget(self.pushButton_next)
        self.widget1 = QtWidgets.QWidget(self.page_video_tab)
        self.widget1.setGeometry(QtCore.QRect(170, 510, 320, 25))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_start = QtWidgets.QPushButton(self.widget1)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_3.addWidget(self.pushButton_start)
        self.pushButton_stop = QtWidgets.QPushButton(self.widget1)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout_3.addWidget(self.pushButton_stop)
        self.pushButton_startRec = QtWidgets.QPushButton(self.widget1)
        self.pushButton_startRec.setObjectName("pushButton_startRec")
        self.horizontalLayout_3.addWidget(self.pushButton_startRec)
        self.pushButton_stopRec = QtWidgets.QPushButton(self.widget1)
        self.pushButton_stopRec.setObjectName("pushButton_stopRec")
        self.horizontalLayout_3.addWidget(self.pushButton_stopRec)
        self.label_player.raise_()
        self.line_2.raise_()
        self.line.raise_()
        self.pushButton_FileDialog.raise_()
        self.label.raise_()
        self.horizontalSlider_video.raise_()
        self.label_vtime.raise_()
        self.tableWidget_Recording.raise_()
        self.stackedWidget.addWidget(self.page_video_tab)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.webView = QtWebKitWidgets.QWebView(self.page_2)
        self.webView.setGeometry(QtCore.QRect(20, 20, 711, 491))
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.stackedWidget.addWidget(self.page_2)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 181, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_page1 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_page1.sizePolicy().hasHeightForWidth())
        self.pushButton_page1.setSizePolicy(sizePolicy)
        self.pushButton_page1.setStyleSheet("background-image: url(:/LoginPage/images/video-icon.jpg);\n"
"\n"
"")
        self.pushButton_page1.setText("")
        self.pushButton_page1.setFlat(False)
        self.pushButton_page1.setObjectName("pushButton_page1")
        self.horizontalLayout.addWidget(self.pushButton_page1)
        self.pushButton_page2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_page2.sizePolicy().hasHeightForWidth())
        self.pushButton_page2.setSizePolicy(sizePolicy)
        self.pushButton_page2.setStyleSheet("background-image: url(:/UserPage/images/quadcopterlogo.png);")
        self.pushButton_page2.setText("")
        self.pushButton_page2.setObjectName("pushButton_page2")
        self.horizontalLayout.addWidget(self.pushButton_page2)
        UserWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UserWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1377, 21))
        self.menubar.setObjectName("menubar")
        UserWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UserWindow)
        self.statusbar.setObjectName("statusbar")
        UserWindow.setStatusBar(self.statusbar)

        self.retranslateUi(UserWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UserWindow)

    def retranslateUi(self, UserWindow):
        _translate = QtCore.QCoreApplication.translate
        UserWindow.setWindowTitle(_translate("UserWindow", "HawkEye"))
        item = self.tableWidget_Recording.horizontalHeaderItem(0)
        item.setText(_translate("UserWindow", "File Name"))
        item = self.tableWidget_Recording.horizontalHeaderItem(1)
        item.setText(_translate("UserWindow", "Date"))
        item = self.tableWidget_Recording.horizontalHeaderItem(2)
        item.setText(_translate("UserWindow", "Time"))
        item = self.tableWidget_Recording.horizontalHeaderItem(3)
        item.setText(_translate("UserWindow", "Duration"))
        self.pushButton_FileDialog.setText(_translate("UserWindow", "OutPut Folder"))
        self.pushButton_prev.setText(_translate("UserWindow", "Prev"))
        self.pushButton_pause.setText(_translate("UserWindow", "Pause"))
        self.pushButton_play.setText(_translate("UserWindow", "Play"))
        self.pushButton_vstop.setText(_translate("UserWindow", "Stop"))
        self.pushButton_next.setText(_translate("UserWindow", "Next"))
        self.pushButton_start.setText(_translate("UserWindow", "Start"))
        self.pushButton_stop.setText(_translate("UserWindow", "Stop"))
        self.pushButton_startRec.setText(_translate("UserWindow", "Start Rec"))
        self.pushButton_stopRec.setText(_translate("UserWindow", "Stop Rec"))


from resource.qrc import LoginPage_rc
from resource.qrc import UserPage_rc
